cargo-features = ["edition2024"]
[package]
name = "keylesslogin"
version = "0.1.0"
edition = "2024"

[dependencies]
expander_compiler={ git="https://github.com/polyhedraZK/ExpanderCompilerCollection", branch="master"}
